#! python3

import webbrowser, sys, requests
#initial request for webpage
webbrowser.open('https://www.abbnow.com/PublicSite/UserAdminTest.htm')

#check for error if page doesn't load
res = requests.get('https://www.abbnow.com/PublicSite/UserAdminTest.htm')
try:
    res.raise_for_status()
except Exception as exc:
    print('There was a problem: %s' % (exc))
    
    
  
